spring.application.name=employee-management-api

# Server port (Render will override this with PORT)
server.port=${PORT:8080}

# Firebase credentials location
firebase.credentials=${FIREBASE_CREDENTIALS}

# Reduce unnecessary logging
logging.level.root=INFO
logging.level.com.nkosinathi.employeemanagement=DEBUG